
The libvoxin library eases the integration of voxin on 64 bits architectures.


* Compil
** Build the libvoxin tarballs
#+BEGIN_SRC shell
./build.sh --release --rfs32=../rfs32
#+END_SRC

../rfs32 is the path to a minimal 32 bits root filesystem including the viavoice binaries (see below).
By default /opt/voxin/rfs32 is used.

** Build with debug symbols + tests
#+BEGIN_SRC shell
./build.sh -tdr ../rfs32
#+END_SRC

** Create a testing directory
#+BEGIN_SRC shell
./test.sh -b
#+END_SRC

** Run test 1
#+BEGIN_SRC shell
./test.sh -t 1
#+END_SRC

** Delete the testing directory
#+BEGIN_SRC shell
./test.sh -d
#+END_SRC

* Minimal rfs32 root filesystem

The 32 bits binaries are now located in rfs32, a dedicated 32 bits directory available globally in /opt/voxin/rfs32 or even locally.

Install the required 32 bits standard libraries (glibc,...) to test libvoxin/voxind.

** viavoice

Install the voxin-viavoice-xxx packages supplied by Oralux.
Note that the conf file eci.ini is now expected in /opt/voxin/rfs32/ and must point to the installed binaries in the rfs32 directory.

** standard 32 bits libraries

These libraries can be built for example by [[https://buildroot.org][Buildroot]] (see its config in src/buildroot/).
Or install the voxin-rfs32 package supplied by Oralux.
The tree is basically :

#+BEGIN_SRC shell
tree rfs32

rfs32
├── lib
│   ├── ld-2.23.so
│   ├── ld-linux.so.2 -> ld-2.23.so
│   ├── libc-2.23.so
│   ├── libc.so.6 -> libc-2.23.so
│   ├── libdl-2.23.so
│   ├── libdl.so.2 -> libdl-2.23.so
│   ├── libm-2.23.so
│   ├── libm.so.6 -> libm-2.23.so
│   ├── libpthread-2.23.so
│   └── libpthread.so.0 -> libpthread-2.23.so
├── lib32 -> lib
└── usr
    ├── bin
    ├── lib
    └── lib32 -> lib


#+END_SRC

* Memo: version 
The program version is stored in src/common/conf.h
